<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <AssemblyName>resty-gui</AssemblyName>
    <RootNamespace>Resty.Gui</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aprillz.MewUI.Windows" Version="0.15.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Resty.Core\Resty.Core.csproj" />
  </ItemGroup>

</Project>
