### Api
GET http://localhost:8080

### PING
GET http://localhost:8080/ping

### HEADERS
GET http://localhost:8080/headers

### COOKIES
GET http://localhost:8080/cookies

### SET-COOKIE
GET http://localhost:8080/set-cookie

### STATUS
GET http://localhost:8080/status/1

### DELAY
GET http://localhost:8080/delay?ms=500

### ECHO
POST http://localhost:8080/echo

